strcasecmp added to mapping
When building for windows if strcasecmp was used the compiler would print
error c3861: 'strcasecmp':identifier not found.
The this can be mapped to the _stricmp function.